# Generated by Django 4.2 on 2026-05-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='banner_image',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
